Functionality to change the project name
NoroffFEU/yeetsheet pull request #147
Opened 2024-10-02 15:11 UTC by DanielEkerhovd

This PR adds functionality to change name of the project. 

Implemented changes:

2024-10-02 21:14 UTC, jonhenrikaavitsland commented on index.html
This menu icon is an intended design and should not be deleted.

2024-10-02 21:16 UTC, jonhenrikaavitsland commented on src/js/spreadsheet/sidebar/projectName.js
We have found the figma files and perhaps we can make some changes to fit the design prototype.

https://www.figma.com/design/N7DYyZAfMzCrilVug7oiYz/Prototype?node-id=474-937&node-type=frame&t=yAAJEhTqZdtjlvJy-0

https://www.figma.com/proto/N7DYyZAfMzCrilVug7oiYz/Prototype?node-id=744-3142

2024-10-02 21:17 UTC, jonhenrikaavitsland requested changes
@DanielEkerhovd 
Please look into the requested changes and request a new review when it has been done. 
Thank you

2024-10-02 22:53 UTC, sulenchy commented on src/js/spreadsheet/sidebar/projectName.js
@jonhenrikaavitsland Can you add this to the doc at `docs/yeetsheet-doc.md`

2024-10-02 22:58 UTC, jonhenrikaavitsland commented on src/js/spreadsheet/sidebar/projectName.js
there should be a ticket to do so already @sulenchy

2024-10-02 23:00 UTC, sulenchy commented on index.html
> +          <p id="proName" class="text-sm uppercase">Project name</p>
Consider the accessibility of the p tag,

how about you try something like

```suggestion
          <p id="proName" contentEditable="true" tabindex="0" role="textbox" aria-label="Editable Project Name" class="text-sm uppercase">Project name</p>
```

2024-10-02 23:01 UTC, sulenchy requested changes
see my comment above

2024-10-02 23:02 UTC, sulenchy commented on src/js/spreadsheet/sidebar/projectName.js
Pls confirm that

2024-10-02 23:14 UTC, jonhenrikaavitsland commented on src/js/spreadsheet/sidebar/projectName.js
There is, ticket [#153](https://github.com/NoroffFEU/yeetsheet/issues/153)

2024-10-03 12:20 UTC, jonhenrikaavitsland approved these changes

2024-10-03 12:20 UTC, jonhenrikaavitsland commented
looks good on my end. 
good work. 
@DanielEkerhovd

2024-10-03 12:20 UTC, merged